#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=test
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/


---
# 开发环境配置
spring:
  profiles: dev
# Server settings
server:
  port: 8080
# svn settings
svn:
  url: 192.168.61.155:11001
  username: JCNEP7340
  password: vincent
---
# 测试环境配置
spring:
  profiles: test
# Server settings
server:
  port: 80
# svn settings
svn:
  url: 192.168.61.155:11001
  username: JCNEP7340
  password: vincent
