#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
---
# 开发环境配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
  profiles: dev
# Server settings
server:
  port: 8080
# svn settings
svn:
  url: 192.168.61.155:11001
---
# 测试环境配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
  profiles: prod
# Server settings
server:
  port: 8888
# svn settings
svn:
  url: 192.168.61.155:11001
