#默认使用dev配置
#java -jar xxx.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
# svn settings
svn:
  url: 192.168.61.155:11001
---
# 开发环境配置
spring:
  profiles: dev
# Server settings
server:
  port: 8888
---
# 测试环境配置
spring:
  profiles: prod
# Server settings
server:
  port: 8888
